CREATE TABLE SEARCH_HISTORY (
	SEARCH_ID INT PRIMARY KEY AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	SEARCH_VALUE VARCHAR(100) NOT NULL,
	CRT_DT VARCHAR(100) NOT NULL,
);

CREATE TABLE USER ( 
	USERNAME VARCHAR(20) PRIMARY KEY, 
	PASSWORD VARCHAR(500), 
	NAME VARCHAR(20), 
	EMAIL VARCHAR(100),
	ISACCOUNTNONEXPIRED BOOLEAN, 
	ISACCOUNTNONLOCKED BOOLEAN, 
	ISCREDENTIALSNONEXPIRED BOOLEAN, 
	ISENABLED BOOLEAN 
);

CREATE TABLE AUTHORITY ( 
	USERNAME VARCHAR(20), 
	AUTHORITY_NAME VARCHAR(20) 
);

